### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jsdhasfedssad** [garrettfoster13/sccmhunter#18]
Hi,

Thank you for this tool!

I am trying to install SCCMHunter in order to test it but I am faced with two issues:

1) Using `pip3 install .` as instructed here does not work. I get the error "ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.". 
2) Using `python3 -m pip install -r requirements.txt` works but building wheel takes about ten minutes.

Am I doing something wrong? If not, can building wheel be sped up?

Thanks!

**Comment by garrettfoster13** [comment]
No, you're not doing anything wrong that's on me. I didn't use poetry for this one and I left the installation instructions as if I had. I updated the readme for how I'm currently running it.

**Comment by b0fhb0fh** [comment]
Hello

after changing README.md I did
pip3 install -r requirements.txt
without any problem (all Requirement already satisfied ) but the tool doesn't start 

# python3 sccmhunter.py         
Traceback (most recent call last):
  File "/opt/sccmhunter/sccmhunter.py", line 2, in <module>
    from lib.commands import admin, find, mssql, smb, http, show, admin, cmpivot
  File "/opt/sccmhunter/lib/commands/http.py", line 2, in <module>
    from lib.attacks.http import HTTP
  File "/opt/sccmhunter/lib/attacks/http.py", line 5, in <module>
    from lib.scripts.sccmwtf import SCCMTools
  File "/opt/sccmhunter/lib/scripts/sccmwtf.py", line 19, in <module>
    from requests_toolbelt.multipart import decoder
  File "/usr/local/lib/python3.11/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/local/lib/python3.11/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/local/lib/python3.11/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/local/lib/python3.11/dist-packages/requests_toolbelt/_compat.py", line 56, in <module>
    from requests.packages.urllib3.contrib.pyopenssl \
  File "/usr/local/lib/python3.11/dist-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3253, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'

Linux kali 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2kali1 (2023-04-18) x86_64 GNU/Linux

Any ideas ?

**Comment by b0fhb0fh** [comment]
Thanks

It looks like pip3 broke some python's packets installed by apt
Kali purple issue
